#!/bin/bash

ARCH=armv7hf

docker build \
     --build-arg ARCH=$ARCH \
     --build-arg PHP_VERSION=$PHP_VERSION \
     --build-arg PHP_VARIANT=$PHP_VARIANT \
     -t $DOCKER_REPO:$PHP_VERSION-$PHP_VARIANT-$ARCH \
     -f $DOCKERFILE_PATH .

ARCH=aarch64

docker build \
     --build-arg ARCH=$ARCH \
     --build-arg PHP_VERSION=$PHP_VERSION \
     --build-arg PHP_VARIANT=$PHP_VARIANT \
     -t $DOCKER_REPO:$PHP_VERSION-$PHP_VARIANT-$ARCH \
     -f $DOCKERFILE_PATH .

ARCH=amd64

docker build \
     --build-arg ARCH=$ARCH \
     --build-arg PHP_VERSION=$PHP_VERSION \
     --build-arg PHP_VARIANT=$PHP_VARIANT \
     -t $DOCKER_REPO:$PHP_VERSION-$PHP_VARIANT-$ARCH \
     -t $DOCKER_REPO:$DOCKER_TAG \
     -f $DOCKERFILE_PATH .