#!/bin/bash
export DOCKER_CLI_EXPERIMENTAL=enabled
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name xbuilder
docker buildx use xbuilder
docker buildx inspect --bootstrap