#!/bin/bash

docker -v

apt-get -y update
apt-get install -y curl qemu-user-static
apt-get install -y --only-upgrade docker-ee

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1

docker version

docker buildx info

docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

docker run \
  --rm \
  --privileged \
  multiarch/qemu-user-static:register --reset

docker buildx info

docker buildx create --name xbuilder
docker buildx use xbuilder
docker buildx inspect --bootstrap
docker buildx ls