#!/bin/bash
apt-get -y update
apt-get -y --only-upgrade install docker-ee

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1

docker info
docker run \
  --rm \
  --privileged \
  multiarch/qemu-user-static:register --reset
echo "##################  start buildx tasks  ##################"
docker buildx ls
echo "##################  Create new buildx builder  ##################"
docker buildx create --name mybuilder
echo "##################  Use new buildx builder  ##################"
docker buildx use mybuilder
echo "##################  Inspect buildx builder  ##################"
docker buildx inspect --bootstrap
echo "################## done with pre_build  ##################"

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker run --rm -t arm64v8/ubuntu uname -m