name: Build Docker Images

on: [push]

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v1
       -
        name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          loginServer: index.docker.io
       -
        name: Build x86_64
        env:
          IMAGE_NAME: fredsl/fred-hardware-php:7.3.12-fpm-amd64
        run: |
          docker pull $IMAGE_NAME || true
          docker build \
               --cache-from $IMAGE_NAME \
               --build-arg PHP_VERSION=7.3.12 \
               --build-arg PHP_VARIANT=fpm-alpine \
               -t $IMAGE_NAME \
                fred-hardware-php
          docker push $IMAGE_NAME

  build-armv7:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          loginServer: index.docker.io
      -
        name: Build ARM v7
        env:
          IMAGE_NAME: fredsl/fred-hardware-php:7.3.12-fpm-armv7hf
        run: |
          docker pull $IMAGE_NAME || true
          bash fred-hardware-php/install-buildx.sh
          docker buildx build \
              --build-arg PHP_VERSION=7.3.12 \
              --build-arg PHP_VARIANT=fpm-alpine \
              --platform linux/arm/v7 \
              -t $IMAGE_NAME \
              --load \
              --file ./fred-hardware-php/Dockerfile ./fred-hardware-php
          docker push $IMAGE_NAME


  build-arm64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          loginServer: index.docker.io
      -
        name: Build ARM 64
        env:
          IMAGE_NAME: fredsl/fred-hardware-php:7.3.12-fpm-aarch64
        run: |
          docker pull $IMAGE_NAME || true
          bash fred-hardware-php/install-buildx.sh
          docker buildx build \
              --cache-from $IMAGE_NAME \
              --build-arg PHP_VERSION=7.3.12 \
              --build-arg PHP_VARIANT=fpm-alpine \
              --platform linux/arm64 \
              -t $IMAGE_NAME \
              --load \
              --file ./fred-hardware-php/Dockerfile ./fred-hardware-php
          docker push $IMAGE_NAME

