name: Build Docker Image

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Install docker buildx
    - uses: actions/checkout@v1
      run: bash fred-hardware-php/install-buildx.sh

    - name: Docker Login
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        loginServer: index.docker.io

  build-armv7:
    needs: setup
    steps:
    - name: build and push armv7 image
      run: |
          ls
          docker buildx build --platform linux/arm/v7 \
          --build-arg PHP_VERSION=7.3.1 \
          --build-arg PHP_VARIANT=fpm \
          -t fredsl/fred-hardware-php:7.3.1-fpm-armv7hf \
          --push fred-hardware-php

  build-arm64:
    needs: setup
    steps:
    - name: build and push arm64 image
      run: |
        ls
        docker buildx build --platform linux/arm64 \
        --build-arg PHP_VERSION=7.3.1 \
        --build-arg PHP_VARIANT=fpm \
        -t fredsl/fred-hardware-php:7.3.1-fpm-aarch64 \
        --push fred-hardware-php
  build-amd64:
    needs: setup
    steps:
    - name: build and push amd64 image
      run: |
        ls
        docker buildx build --platform linux/amd64 \
        --build-arg PHP_VERSION=7.3.1 \
        --build-arg PHP_VARIANT=fpm \
        -t fredsl/fred-hardware-php:7.3.1-fpm-amd64 \
        --push fred-hardware-php
