name: Build Docker Image

on: [push]

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v1
       -
        name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          loginServer: index.docker.io
       -
        name: Build x86_64
        run: |
             docker build \
             --build-arg PHP_VERSION=7.3.1 \
             --build-arg PHP_VARIANT=fpm \
             -t fredsl/fred-hardware-php:7.3.1-fpm-amd64 \
              fred-hardware-php

  build-armv7:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install docker buildx
        run: bash fred-hardware-php/install-buildx.sh
      -
        name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          loginServer: index.docker.io
      -
        name: Build ARM v7
        run: |
            docker buildx build \
            --build-arg PHP_VERSION=7.3.1 \
            --build-arg PHP_VARIANT=fpm \
            --platform linux/armv7hf \
            -t fredsl/fred-hardware-php:7.3.1-fpm-armv7hf \
            --push \
            --file ./fred-hardware-php/Dockerfile ./fred-hardware-php

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install docker buildx
        run: bash fred-hardware-php/install-buildx.sh
      -
        name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          loginServer: index.docker.io
      -
        name: Build ARM 64
        run: |
            docker buildx build \
            --build-arg PHP_VERSION=7.3.1 \
            --build-arg PHP_VARIANT=fpm \
            --platform linux/arm64 \
            -t fredsl/fred-hardware-php:7.3.1-fpm-aarch64 \
            --push \
            --file ./fred-hardware-php/Dockerfile ./fred-hardware-php
