name: Build Docker Image

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install docker buildx
      run: bash fred-hardware-php/install-buildx.sh

  build-armv7:
    needs: setup
    steps:
    - name: build and push armv7 image
    - uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        loginServer: index.docker.io
      run: |
          ls
          docker buildx build --platform linux/arm/v7 \
          --build-arg PHP_VERSION=7.3.1 \
          --build-arg PHP_VARIANT=fpm \
          -t fredsl/fred-hardware-php:7.3.1-fpm-armv7hf \
          --push fred-hardware-php
  build-arm64:
    needs: setup
    steps:
    - name: build and push arm64 image
    - uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        loginServer: index.docker.io
      run: |
        ls
        docker buildx build --platform linux/arm64 \
        --build-arg PHP_VERSION=7.3.1 \
        --build-arg PHP_VARIANT=fpm \
        -t fredsl/fred-hardware-php:7.3.1-fpm-aarch64 \
        --push fred-hardware-php
  build-amd64:
    needs: setup
    steps:
    - name: build and push amd64 image
    - uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        loginServer: index.docker.io
      run: |
        ls
        docker buildx build --platform linux/amd64 \
        --build-arg PHP_VERSION=7.3.1 \
        --build-arg PHP_VARIANT=fpm \
        -t fredsl/fred-hardware-php:7.3.1-fpm-amd64 \
        --push fred-hardware-php
