name: Build Docker Image

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v1
       -
        name: Install docker buildx
        run: bash fred-hardware-php/install-buildx.sh
       -
        name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          loginServer: index.docker.io
        
  build-amd64:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: build and push amd64 image
      run: |
        docker buildx build \
          --build-arg PHP_VERSION=7.3.1 \
          --build-arg PHP_VARIANT=fpm \
          --platform linux/amd64 \
          -t fredsl/fred-hardware-php:7.3.1-fpm-amd64 \
          --push \
          --file ./fred-hardware-php/Dockerfile ./fred-hardware-php
